# Generated by Django 3.2.23 on 2024-02-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20240208_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='image_2',
            field=models.BinaryField(blank=True, help_text='Image of user face', null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='image_2',
            field=models.BinaryField(blank=True, help_text='The image from door device', null=True),
        ),
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/face'),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/history'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image2',
            field=models.BinaryField(blank=True, help_text='Image of user face', null=True),
        ),
    ]
