# Generated by Django 3.2.23 on 2024-02-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20240209_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='history',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_image2',
        ),
        migrations.AlterField(
            model_name='face',
            name='image',
            field=models.BinaryField(blank=True, help_text='Image of user face', null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.BinaryField(blank=True, help_text='The image from door device', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.BinaryField(blank=True, help_text='Image of user face', null=True),
        ),
    ]
